version: "3.8"
services:
    # Database server
    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: ~
